// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jbkrndaekjrpskkwnjjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impia3JuZGFla2pycHNra3duamp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0NTU2MzMsImV4cCI6MjA2NDAzMTYzM30.4hffr2OMrRqpMFWu0umUVz-XBYYsosnDwM827THk6XQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);